create database healthcare;
use healthcare;

select * from patients limit 5;

select * from admissions limit 5;

select * from doctors limit 5;

select * from billing limit 5;

select * from hospitals limit 5;

-- patients - (patientid (PK), firtname, lastname, age, gender, bloodtype, full_name)
-- admissions - (admissionid (PK), patientid (FK), doctorid (FK), admissiondate, dischargedate, diagnosis, department, admissiondays, stay_category)
-- doctors - (doctorid (PK), firstname, specialty, yearsofexperience)
-- billing - (billID (PK), admissionid (FK), totalcost, diagnosis_cost, room_cost, pharmacy_cost, doctor_fee, insurancecovered, paymentstatus)
-- hospitals - (hospitalid (PK), hospitalname, city, region)


-- Q1) Write a query to retrieve the First Name, Last Name, and 
-- Age of all patients who have been admitted by a doctor with more 
-- than 20 years of experience.

select distinct firstname, lastname, age
from patients
where patientid in 
(select patientid from admissions
where doctorid in 
(select doctorid from doctors where yearsofexperience > 20));

-- Q2) Calculate the total gross revenue (TotalCost) generated by each 
-- hospital region (North, South, East, etc.).

with hospital_revenue as 
(select a.hospitalid, sum(b.totalcost) as total_revenue
from billing b
join admissions a on b.admissionid = a.admissionid
group by a.hospitalid)
select h.region, round(sum(hr.total_revenue),2) as regional_gross_revenue
from hospital_revenue hr
join hospitals h on hr.hospitalid = h.hospitalid
group by h.region;

-- Q3) Identify all patients whose total lifetime billed amount (across all their hospital visits) 
-- is strictly greater than the average lifetime billed amount of all patients in the database.

with patient_totals as 
(select a.patientid, round(sum(b.totalcost),2) as lifetime_billed
from admissions a
join billing b on a.admissionid = b.admissionid
group by a.patientid)
select p.patientid, p.firstname, p.lastname, pt.lifetime_billed
from patient_totals pt
join patients p on pt.patientid = p.patientid
where pt.lifetime_billed > (select avg(lifetime_billed) from patient_totals);

-- Q4) Identify the names of doctors who have treated patients 
-- with a 'Diabetes' diagnosis, along with the total revenue 
-- generated by those specific admissions.

select d.firstname as doctor_name, round(sum(b.totalcost),2) as total_revenue
from doctors d join admissions a on d.doctorid = a.doctorid
join billing b on b.admissionid = a.admissionid
where a.diagnosis = 'Diabetes'
group by d.doctorid, d.firstname;

-- Q5) Write a query to identify which hospitals have an Average Admission Days 
-- that is strictly greater than the overall network's Average Admission Days.

with hospital_avg as 
(select h.hospitalname, round(avg(a.admissiondays),2) as avg_hospital_days
from admissions a
join hospitals h on a.hospitalid = h.hospitalid
group by h.hospitalname, h.hospitalid)
select hospitalname, avg_hospital_days
from hospital_avg
where avg_hospital_days > (select avg(admissiondays) from admissions);

-- Q6) Find pairs of doctors who work in the exact same hospital and 
-- share the exact same specialty.

select d1.doctorid as doctor1_id, d1.firstname as doctor1_name, 
d2.doctorid as doctor2_id, d2.firstname as doctor2_name, d1.specialty, 
d1.hospitalid
from doctors d1
join doctors d2 on d1.hospitalid = d2.hospitalid
where d1.specialty = d2.specialty and d1.doctorid < d2.doctorid;

-- Q7) Identify "Frequent Flyers" (patients with more than 3 admissions 
-- in a single year) and their most common diagnosis.

with yearly_admission as
( select patientid, year(admissiondate) as admission_year, 
count(admissionid) as total_admissions
from admissions 
group by patientid, year(admissiondate)
having count(admissionid) > 3),
diagnosis_rnk as
( select a.patientid, a.diagnosis, count(a.admissionid) as diagnosis_count,
row_number() over(partition by a.patientid order by count(a.admissionid) desc) as rnk
from admissions a join yearly_admission ya on a.patientid = ya.patientid
group by a.patientid, a.diagnosis)
select p.full_name, ya.admission_year, ya.total_admissions, 
dr.diagnosis as most_common_diagnosis
from yearly_admission ya join diagnosis_rnk dr on ya.patientid = dr.patientid
join patients p on ya.patientid = p.patientid
where dr.rnk = 1;


-- Q8) Rank doctors within each Specialty based on the total number 
-- of patients they have treated using DENSE_RANK().

with dpc as
(select d.doctorid, d.firstname as Doctor_Name,
d.specialty, count(a.admissionid) as total_patients_treated
from doctors d join admissions a on a.doctorid = d.doctorid
group by d.doctorid, d.firstname, d.specialty)
select 
dense_rank() over(partition by specialty order by total_patients_treated desc) as Doctor_rnk,
Doctor_Name, specialty, total_patients_treated
from dpc
order by specialty, Doctor_rnk;

-- Q9) Calculate the month-over-month percentage change in total cleared revenue 
-- for the entire hospital network.

with monthly_revenue as 
(select year(a.admissiondate) as rev_year,
month(a.admissiondate) as rev_month, sum(b.totalcost) as current_revenue
from billing b
join admissions a on b.admissionid = a.admissionid
where b.paymentstatus = 'cleared'
group by year(a.admissiondate),month(a.admissiondate)),
revenue_with_lag as 
(select rev_year, rev_month, current_revenue,
lag(current_revenue) over (order by rev_year, rev_month) as prev_revenue
from monthly_revenue)
select rev_year, rev_month, current_revenue, prev_revenue,
round(((current_revenue - prev_revenue) / prev_revenue) * 100, 2) as mom_percent_change
from revenue_with_lag;

-- Q10) Find all instances where a patient was readmitted to the hospital 
-- within 30 days of their previous discharge date. Return the PatientID, 
-- the previous DischargeDate, and the new AdmissionDate.

with readmissions as 
(select patientid, admissiondate as new_admissiondate,
lag(dischargedate) over (partition by patientid order by admissiondate) as prev_dischargedate
from admissions)
select 
patientid, prev_dischargedate, new_admissiondate
from readmissions
where prev_dischargedate is not null
and datediff(new_admissiondate, prev_dischargedate) <= 30;

-- Q11) Identify the "Star Doctor" of each region. A Star Doctor is defined as 
-- the one who generated the absolute highest total revenue in their specific 
-- region. Return the Region, Hospital Name, Doctor Name, and Total Revenue.

with doctor_revenue as 
(select h.region, h.hospitalname, d.firstname as doctor_name, sum(b.totalcost) as total_revenue
from doctors d join admissions a on d.doctorid = a.doctorid
join billing b on a.admissionid = b.admissionid
join hospitals h on d.hospitalid = h.hospitalid
group by h.region, h.hospitalname, d.doctorid, d.firstname),
ranked_doctors as 
(select region, hospitalname, doctor_name, total_revenue,
dense_rank() over (partition by region order by total_revenue desc) as rnk
from doctor_revenue)
select region, hospitalname, doctor_name, total_revenue
from ranked_doctors
where rnk = 1;

-- Q12) Create a Stored Procedure named GetDoctorStats that takes a specific DoctorID 
-- as an input parameter. When called, it should return a summary containing:
-- The doctor's name and specialty.
-- The total number of unique patients they have treated.
-- The average admission days (in days) for their patients.
-- The total revenue they have generated.

delimiter //

create procedure getdoctorstats(in p_doctorid varchar(50))
begin
select d.firstname as doctor_name, d.specialty,
count(distinct a.patientid) as total_unique_patients,
round(avg(a.admissiondays),2) as average_admission_days,
round(sum(b.totalcost),2) as total_revenue
from doctors d join admissions a on d.doctorid = a.doctorid
join billing b on a.admissionid = b.admissionid
where d.doctorid = p_doctorid
group by d.firstname, d.specialty;
end //

delimiter ;

call getdoctorstats('DR-0337');

-- Q13) Create a Stored Procedure that takes a PatientID as an input and 
-- returns their complete medical history, including all past diagnoses, 
-- attending doctors, and total lifetime cost.

delimiter //

create procedure getpatientmedicalhistory(in p_patientid varchar(50))
begin
select a.admissiondate, a.dischargedate,
a.diagnosis, d.firstname as attending_doctor,
d.specialty, b.totalcost as admission_cost,
round(sum(b.totalcost) over (partition by a.patientid),2) as lifetime_total_cost
from admissions a join doctors d on a.doctorid = d.doctorid
join billing b on a.admissionid = b.admissionid
where a.patientid = p_patientid
order by a.admissiondate desc;
end //

delimiter ;

call getpatientmedicalhistory('184-63-2956');